CREATE TABLE MYWEATHER (
	SEQ INT AUTO_INCREMENT PRIMARY KEY,
	INSERT_DATE DATETIME NOT NULL,
	BASE_DATE CHAR(8) NOT NULL,
    BASE_TIME CHAR(4) NOT NULL,
	FCST_DATE CHAR(8) NOT NULL,
    FCST_TIME CHAR(4) NOT NULL,
	REH_VAL CHAR(2) NOT NULL,
    TMP_VAL CHAR(2) NOT NULL
);
SELECT * FROM MYWEATHER;
DROP TABLE MYWEATHER;
DELETE FROM MYWEATHER;

INSERT INTO myweather(insertdate, base_date, base_time, 
fcst_date,fcst_time, reh_val, tmp_val) 
VALUES 
   ("20220611","2222","T1H",33) 
ON DUPLICATE KEY UPDATE fcstvalue = 55;


INSERT INTO MYWEATHER (BASE_DATE, BASE_TIME,  CATEGORY, FCST_DATE, FCST_TIME, FCST_VALUE)
SELECT '20220612', 'T1H' FROM DUAL
WHERE NOT EXISTS (
SELECT FCST_DATE FROM MYWEATHER WHERE 
FCST_DATE = '20220612' AND CATEGORY = 'T1H' ) LIMIT 1;

INSERT INTO myweather (CATEGORY,FCSTDATE,FCSTTIME,FCSTVALUE)
SELECT CATEGORY,FCSTDATE,FCSTTIME,FCSTVALUE
FROM (SELECT "REM" as CATEGORY, 
"20220611" as FCSTDATE ) t
WHERE NOT EXISTS (SELECT 1=1 FROM myweather u 
WHERE u.category = t.category AND u.fcstdate=t.fcstdate);